secrets:
  db_pass: 
    file: ./secrets/db_pass.txt
  db_user:
    file: ./secrets/db_user.txt
  db_name:
    file: ./secrets/db_name.txt
  wp_admin_pass:
    file: ./secrets/wp_admin_pass.txt
  wp_admin_name:
    file: ./secrets/wp_admin_name.txt
  wp_admin_email:
    file: ./secrets/wp_admin_email.txt
  wp_user_pass:
    file: ./secrets/wp_user_pass.txt

services:
  mariadb:
    build: ./srcs/requirements/mariadb
    container_name: mariadb
    pull_policy: never
    secrets:
      - db_name
      - db_pass
      - db_user
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    
  wordpress:
    build: ./srcs/requirements/wordpress
    container_name: wordpress
    pull_policy: never
    secrets:
      - wp_admin_name
      - wp_admin_email
      - wp_admin_pass
      - wp_user_pass
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
  nginx:
    build: ./srcs/requirements/nginx
    container_name: nginx
    pull_policy: never
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/gilsonchipombo/data/data_
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/gilsonchipombo/data/wordpress_
      o: bind

networks:
  inception: